// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service/chess.proto

package chess

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UciRequest_MessageType int32

const (
	UciRequest_ID             UciRequest_MessageType = 0
	UciRequest_OPTION         UciRequest_MessageType = 1
	UciRequest_UCIOK          UciRequest_MessageType = 2
	UciRequest_READYOK        UciRequest_MessageType = 3
	UciRequest_BESTMOVE       UciRequest_MessageType = 4
	UciRequest_COPYPROTECTION UciRequest_MessageType = 5
	UciRequest_REGISTRATION   UciRequest_MessageType = 6
	UciRequest_INFO           UciRequest_MessageType = 7
)

var UciRequest_MessageType_name = map[int32]string{
	0: "ID",
	1: "OPTION",
	2: "UCIOK",
	3: "READYOK",
	4: "BESTMOVE",
	5: "COPYPROTECTION",
	6: "REGISTRATION",
	7: "INFO",
}

var UciRequest_MessageType_value = map[string]int32{
	"ID":             0,
	"OPTION":         1,
	"UCIOK":          2,
	"READYOK":        3,
	"BESTMOVE":       4,
	"COPYPROTECTION": 5,
	"REGISTRATION":   6,
	"INFO":           7,
}

func (x UciRequest_MessageType) String() string {
	return proto.EnumName(UciRequest_MessageType_name, int32(x))
}

func (UciRequest_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cdc17040449aa6b8, []int{0, 0}
}

type UciResponse_MessageType int32

const (
	UciResponse_UCI        UciResponse_MessageType = 0
	UciResponse_DEBUG      UciResponse_MessageType = 1
	UciResponse_ISREADY    UciResponse_MessageType = 2
	UciResponse_SETOPTION  UciResponse_MessageType = 3
	UciResponse_REGISTER   UciResponse_MessageType = 4
	UciResponse_UCINEWGAME UciResponse_MessageType = 5
	UciResponse_POSITION   UciResponse_MessageType = 6
	UciResponse_GO         UciResponse_MessageType = 7
	UciResponse_STOP       UciResponse_MessageType = 8
	UciResponse_PONDERHIT  UciResponse_MessageType = 9
	UciResponse_QUIT       UciResponse_MessageType = 10
)

var UciResponse_MessageType_name = map[int32]string{
	0:  "UCI",
	1:  "DEBUG",
	2:  "ISREADY",
	3:  "SETOPTION",
	4:  "REGISTER",
	5:  "UCINEWGAME",
	6:  "POSITION",
	7:  "GO",
	8:  "STOP",
	9:  "PONDERHIT",
	10: "QUIT",
}

var UciResponse_MessageType_value = map[string]int32{
	"UCI":        0,
	"DEBUG":      1,
	"ISREADY":    2,
	"SETOPTION":  3,
	"REGISTER":   4,
	"UCINEWGAME": 5,
	"POSITION":   6,
	"GO":         7,
	"STOP":       8,
	"PONDERHIT":  9,
	"QUIT":       10,
}

func (x UciResponse_MessageType) String() string {
	return proto.EnumName(UciResponse_MessageType_name, int32(x))
}

func (UciResponse_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cdc17040449aa6b8, []int{1, 0}
}

type GameMessageResponse_GameMessageResponseTypes int32

const (
	GameMessageResponse_OK           GameMessageResponse_GameMessageResponseTypes = 0
	GameMessageResponse_ILLEGAL_MOVE GameMessageResponse_GameMessageResponseTypes = 1
)

var GameMessageResponse_GameMessageResponseTypes_name = map[int32]string{
	0: "OK",
	1: "ILLEGAL_MOVE",
}

var GameMessageResponse_GameMessageResponseTypes_value = map[string]int32{
	"OK":           0,
	"ILLEGAL_MOVE": 1,
}

func (x GameMessageResponse_GameMessageResponseTypes) String() string {
	return proto.EnumName(GameMessageResponse_GameMessageResponseTypes_name, int32(x))
}

func (GameMessageResponse_GameMessageResponseTypes) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cdc17040449aa6b8, []int{10, 0}
}

type ClientGameMessage_MessageType int32

const (
	ClientGameMessage_UCI                ClientGameMessage_MessageType = 0
	ClientGameMessage_GAME_STATE_REQUEST ClientGameMessage_MessageType = 1
)

var ClientGameMessage_MessageType_name = map[int32]string{
	0: "UCI",
	1: "GAME_STATE_REQUEST",
}

var ClientGameMessage_MessageType_value = map[string]int32{
	"UCI":                0,
	"GAME_STATE_REQUEST": 1,
}

func (x ClientGameMessage_MessageType) String() string {
	return proto.EnumName(ClientGameMessage_MessageType_name, int32(x))
}

func (ClientGameMessage_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cdc17040449aa6b8, []int{11, 0}
}

type ServerGameMessage_MessageType int32

const (
	ServerGameMessage_UCI                 ServerGameMessage_MessageType = 0
	ServerGameMessage_GAME_STATE_RESPONSE ServerGameMessage_MessageType = 1
)

var ServerGameMessage_MessageType_name = map[int32]string{
	0: "UCI",
	1: "GAME_STATE_RESPONSE",
}

var ServerGameMessage_MessageType_value = map[string]int32{
	"UCI":                 0,
	"GAME_STATE_RESPONSE": 1,
}

func (x ServerGameMessage_MessageType) String() string {
	return proto.EnumName(ServerGameMessage_MessageType_name, int32(x))
}

func (ServerGameMessage_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cdc17040449aa6b8, []int{15, 0}
}

type UciRequest struct {
	MessageType          UciRequest_MessageType `protobuf:"varint,1,opt,name=messageType,proto3,enum=UciRequest_MessageType" json:"messageType,omitempty"`
	Id                   *UciRequest_Id         `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	BestMove             *UciRequest_BestMove   `protobuf:"bytes,3,opt,name=bestMove,proto3" json:"bestMove,omitempty"`
	Info                 *UciRequest_Info       `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
	Option               *UciRequest_Option     `protobuf:"bytes,5,opt,name=option,proto3" json:"option,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UciRequest) Reset()         { *m = UciRequest{} }
func (m *UciRequest) String() string { return proto.CompactTextString(m) }
func (*UciRequest) ProtoMessage()    {}
func (*UciRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdc17040449aa6b8, []int{0}
}

func (m *UciRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UciRequest.Unmarshal(m, b)
}
func (m *UciRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UciRequest.Marshal(b, m, deterministic)
}
func (m *UciRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UciRequest.Merge(m, src)
}
func (m *UciRequest) XXX_Size() int {
	return xxx_messageInfo_UciRequest.Size(m)
}
func (m *UciRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UciRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UciRequest proto.InternalMessageInfo

func (m *UciRequest) GetMessageType() UciRequest_MessageType {
	if m != nil {
		return m.MessageType
	}
	return UciRequest_ID
}

func (m *UciRequest) GetId() *UciRequest_Id {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *UciRequest) GetBestMove() *UciRequest_BestMove {
	if m != nil {
		return m.BestMove
	}
	return nil
}

func (m *UciRequest) GetInfo() *UciRequest_Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *UciRequest) GetOption() *UciRequest_Option {
	if m != nil {
		return m.Option
	}
	return nil
}

type UciRequest_Option struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Default              string   `protobuf:"bytes,3,opt,name=default,proto3" json:"default,omitempty"`
	Min                  int32    `protobuf:"varint,4,opt,name=min,proto3" json:"min,omitempty"`
	Max                  int32    `protobuf:"varint,5,opt,name=max,proto3" json:"max,omitempty"`
	Var                  []string `protobuf:"bytes,6,rep,name=var,proto3" json:"var,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UciRequest_Option) Reset()         { *m = UciRequest_Option{} }
func (m *UciRequest_Option) String() string { return proto.CompactTextString(m) }
func (*UciRequest_Option) ProtoMessage()    {}
func (*UciRequest_Option) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdc17040449aa6b8, []int{0, 0}
}

func (m *UciRequest_Option) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UciRequest_Option.Unmarshal(m, b)
}
func (m *UciRequest_Option) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UciRequest_Option.Marshal(b, m, deterministic)
}
func (m *UciRequest_Option) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UciRequest_Option.Merge(m, src)
}
func (m *UciRequest_Option) XXX_Size() int {
	return xxx_messageInfo_UciRequest_Option.Size(m)
}
func (m *UciRequest_Option) XXX_DiscardUnknown() {
	xxx_messageInfo_UciRequest_Option.DiscardUnknown(m)
}

var xxx_messageInfo_UciRequest_Option proto.InternalMessageInfo

func (m *UciRequest_Option) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UciRequest_Option) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *UciRequest_Option) GetDefault() string {
	if m != nil {
		return m.Default
	}
	return ""
}

func (m *UciRequest_Option) GetMin() int32 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *UciRequest_Option) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *UciRequest_Option) GetVar() []string {
	if m != nil {
		return m.Var
	}
	return nil
}

type UciRequest_Id struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Author               string   `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UciRequest_Id) Reset()         { *m = UciRequest_Id{} }
func (m *UciRequest_Id) String() string { return proto.CompactTextString(m) }
func (*UciRequest_Id) ProtoMessage()    {}
func (*UciRequest_Id) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdc17040449aa6b8, []int{0, 1}
}

func (m *UciRequest_Id) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UciRequest_Id.Unmarshal(m, b)
}
func (m *UciRequest_Id) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UciRequest_Id.Marshal(b, m, deterministic)
}
func (m *UciRequest_Id) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UciRequest_Id.Merge(m, src)
}
func (m *UciRequest_Id) XXX_Size() int {
	return xxx_messageInfo_UciRequest_Id.Size(m)
}
func (m *UciRequest_Id) XXX_DiscardUnknown() {
	xxx_messageInfo_UciRequest_Id.DiscardUnknown(m)
}

var xxx_messageInfo_UciRequest_Id proto.InternalMessageInfo

func (m *UciRequest_Id) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UciRequest_Id) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

type UciRequest_BestMove struct {
	Ponder               []string `protobuf:"bytes,1,rep,name=ponder,proto3" json:"ponder,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UciRequest_BestMove) Reset()         { *m = UciRequest_BestMove{} }
func (m *UciRequest_BestMove) String() string { return proto.CompactTextString(m) }
func (*UciRequest_BestMove) ProtoMessage()    {}
func (*UciRequest_BestMove) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdc17040449aa6b8, []int{0, 2}
}

func (m *UciRequest_BestMove) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UciRequest_BestMove.Unmarshal(m, b)
}
func (m *UciRequest_BestMove) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UciRequest_BestMove.Marshal(b, m, deterministic)
}
func (m *UciRequest_BestMove) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UciRequest_BestMove.Merge(m, src)
}
func (m *UciRequest_BestMove) XXX_Size() int {
	return xxx_messageInfo_UciRequest_BestMove.Size(m)
}
func (m *UciRequest_BestMove) XXX_DiscardUnknown() {
	xxx_messageInfo_UciRequest_BestMove.DiscardUnknown(m)
}

var xxx_messageInfo_UciRequest_BestMove proto.InternalMessageInfo

func (m *UciRequest_BestMove) GetPonder() []string {
	if m != nil {
		return m.Ponder
	}
	return nil
}

type UciRequest_Score struct {
	Cp                   int32    `protobuf:"varint,1,opt,name=cp,proto3" json:"cp,omitempty"`
	Mate                 int32    `protobuf:"varint,2,opt,name=mate,proto3" json:"mate,omitempty"`
	Lower                int32    `protobuf:"varint,3,opt,name=lower,proto3" json:"lower,omitempty"`
	Upper                int32    `protobuf:"varint,4,opt,name=upper,proto3" json:"upper,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UciRequest_Score) Reset()         { *m = UciRequest_Score{} }
func (m *UciRequest_Score) String() string { return proto.CompactTextString(m) }
func (*UciRequest_Score) ProtoMessage()    {}
func (*UciRequest_Score) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdc17040449aa6b8, []int{0, 3}
}

func (m *UciRequest_Score) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UciRequest_Score.Unmarshal(m, b)
}
func (m *UciRequest_Score) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UciRequest_Score.Marshal(b, m, deterministic)
}
func (m *UciRequest_Score) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UciRequest_Score.Merge(m, src)
}
func (m *UciRequest_Score) XXX_Size() int {
	return xxx_messageInfo_UciRequest_Score.Size(m)
}
func (m *UciRequest_Score) XXX_DiscardUnknown() {
	xxx_messageInfo_UciRequest_Score.DiscardUnknown(m)
}

var xxx_messageInfo_UciRequest_Score proto.InternalMessageInfo

func (m *UciRequest_Score) GetCp() int32 {
	if m != nil {
		return m.Cp
	}
	return 0
}

func (m *UciRequest_Score) GetMate() int32 {
	if m != nil {
		return m.Mate
	}
	return 0
}

func (m *UciRequest_Score) GetLower() int32 {
	if m != nil {
		return m.Lower
	}
	return 0
}

func (m *UciRequest_Score) GetUpper() int32 {
	if m != nil {
		return m.Upper
	}
	return 0
}

type UciRequest_Info struct {
	Depth                uint32            `protobuf:"varint,1,opt,name=depth,proto3" json:"depth,omitempty"`
	Seldepth             uint32            `protobuf:"varint,2,opt,name=seldepth,proto3" json:"seldepth,omitempty"`
	Time                 uint32            `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	Nodes                uint32            `protobuf:"varint,4,opt,name=nodes,proto3" json:"nodes,omitempty"`
	Pv                   int32             `protobuf:"varint,5,opt,name=pv,proto3" json:"pv,omitempty"`
	Multipv              int32             `protobuf:"varint,6,opt,name=multipv,proto3" json:"multipv,omitempty"`
	Score                *UciRequest_Score `protobuf:"bytes,7,opt,name=score,proto3" json:"score,omitempty"`
	Currmove             string            `protobuf:"bytes,8,opt,name=currmove,proto3" json:"currmove,omitempty"`
	Currmovenumber       uint32            `protobuf:"varint,9,opt,name=currmovenumber,proto3" json:"currmovenumber,omitempty"`
	Hashfull             uint32            `protobuf:"varint,10,opt,name=hashfull,proto3" json:"hashfull,omitempty"`
	Nps                  uint32            `protobuf:"varint,11,opt,name=nps,proto3" json:"nps,omitempty"`
	Tbhits               uint32            `protobuf:"varint,12,opt,name=tbhits,proto3" json:"tbhits,omitempty"`
	Cpuload              uint32            `protobuf:"varint,13,opt,name=cpuload,proto3" json:"cpuload,omitempty"`
	String_              string            `protobuf:"bytes,14,opt,name=string,proto3" json:"string,omitempty"`
	Refutation           []string          `protobuf:"bytes,15,rep,name=refutation,proto3" json:"refutation,omitempty"`
	Currline             string            `protobuf:"bytes,16,opt,name=currline,proto3" json:"currline,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UciRequest_Info) Reset()         { *m = UciRequest_Info{} }
func (m *UciRequest_Info) String() string { return proto.CompactTextString(m) }
func (*UciRequest_Info) ProtoMessage()    {}
func (*UciRequest_Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdc17040449aa6b8, []int{0, 4}
}

func (m *UciRequest_Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UciRequest_Info.Unmarshal(m, b)
}
func (m *UciRequest_Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UciRequest_Info.Marshal(b, m, deterministic)
}
func (m *UciRequest_Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UciRequest_Info.Merge(m, src)
}
func (m *UciRequest_Info) XXX_Size() int {
	return xxx_messageInfo_UciRequest_Info.Size(m)
}
func (m *UciRequest_Info) XXX_DiscardUnknown() {
	xxx_messageInfo_UciRequest_Info.DiscardUnknown(m)
}

var xxx_messageInfo_UciRequest_Info proto.InternalMessageInfo

func (m *UciRequest_Info) GetDepth() uint32 {
	if m != nil {
		return m.Depth
	}
	return 0
}

func (m *UciRequest_Info) GetSeldepth() uint32 {
	if m != nil {
		return m.Seldepth
	}
	return 0
}

func (m *UciRequest_Info) GetTime() uint32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *UciRequest_Info) GetNodes() uint32 {
	if m != nil {
		return m.Nodes
	}
	return 0
}

func (m *UciRequest_Info) GetPv() int32 {
	if m != nil {
		return m.Pv
	}
	return 0
}

func (m *UciRequest_Info) GetMultipv() int32 {
	if m != nil {
		return m.Multipv
	}
	return 0
}

func (m *UciRequest_Info) GetScore() *UciRequest_Score {
	if m != nil {
		return m.Score
	}
	return nil
}

func (m *UciRequest_Info) GetCurrmove() string {
	if m != nil {
		return m.Currmove
	}
	return ""
}

func (m *UciRequest_Info) GetCurrmovenumber() uint32 {
	if m != nil {
		return m.Currmovenumber
	}
	return 0
}

func (m *UciRequest_Info) GetHashfull() uint32 {
	if m != nil {
		return m.Hashfull
	}
	return 0
}

func (m *UciRequest_Info) GetNps() uint32 {
	if m != nil {
		return m.Nps
	}
	return 0
}

func (m *UciRequest_Info) GetTbhits() uint32 {
	if m != nil {
		return m.Tbhits
	}
	return 0
}

func (m *UciRequest_Info) GetCpuload() uint32 {
	if m != nil {
		return m.Cpuload
	}
	return 0
}

func (m *UciRequest_Info) GetString_() string {
	if m != nil {
		return m.String_
	}
	return ""
}

func (m *UciRequest_Info) GetRefutation() []string {
	if m != nil {
		return m.Refutation
	}
	return nil
}

func (m *UciRequest_Info) GetCurrline() string {
	if m != nil {
		return m.Currline
	}
	return ""
}

type UciResponse struct {
	MessageType          UciResponse_MessageType `protobuf:"varint,1,opt,name=messageType,proto3,enum=UciResponse_MessageType" json:"messageType,omitempty"`
	Debug                bool                    `protobuf:"varint,2,opt,name=debug,proto3" json:"debug,omitempty"`
	SetOption            *UciResponse_SetOption  `protobuf:"bytes,3,opt,name=setOption,proto3" json:"setOption,omitempty"`
	Position             *UciResponse_Position   `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *UciResponse) Reset()         { *m = UciResponse{} }
func (m *UciResponse) String() string { return proto.CompactTextString(m) }
func (*UciResponse) ProtoMessage()    {}
func (*UciResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdc17040449aa6b8, []int{1}
}

func (m *UciResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UciResponse.Unmarshal(m, b)
}
func (m *UciResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UciResponse.Marshal(b, m, deterministic)
}
func (m *UciResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UciResponse.Merge(m, src)
}
func (m *UciResponse) XXX_Size() int {
	return xxx_messageInfo_UciResponse.Size(m)
}
func (m *UciResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UciResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UciResponse proto.InternalMessageInfo

func (m *UciResponse) GetMessageType() UciResponse_MessageType {
	if m != nil {
		return m.MessageType
	}
	return UciResponse_UCI
}

func (m *UciResponse) GetDebug() bool {
	if m != nil {
		return m.Debug
	}
	return false
}

func (m *UciResponse) GetSetOption() *UciResponse_SetOption {
	if m != nil {
		return m.SetOption
	}
	return nil
}

func (m *UciResponse) GetPosition() *UciResponse_Position {
	if m != nil {
		return m.Position
	}
	return nil
}

type UciResponse_SetOption struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UciResponse_SetOption) Reset()         { *m = UciResponse_SetOption{} }
func (m *UciResponse_SetOption) String() string { return proto.CompactTextString(m) }
func (*UciResponse_SetOption) ProtoMessage()    {}
func (*UciResponse_SetOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdc17040449aa6b8, []int{1, 0}
}

func (m *UciResponse_SetOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UciResponse_SetOption.Unmarshal(m, b)
}
func (m *UciResponse_SetOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UciResponse_SetOption.Marshal(b, m, deterministic)
}
func (m *UciResponse_SetOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UciResponse_SetOption.Merge(m, src)
}
func (m *UciResponse_SetOption) XXX_Size() int {
	return xxx_messageInfo_UciResponse_SetOption.Size(m)
}
func (m *UciResponse_SetOption) XXX_DiscardUnknown() {
	xxx_messageInfo_UciResponse_SetOption.DiscardUnknown(m)
}

var xxx_messageInfo_UciResponse_SetOption proto.InternalMessageInfo

func (m *UciResponse_SetOption) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UciResponse_SetOption) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type UciResponse_Position struct {
	IsFen                bool     `protobuf:"varint,1,opt,name=isFen,proto3" json:"isFen,omitempty"`
	Moves                []string `protobuf:"bytes,2,rep,name=moves,proto3" json:"moves,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UciResponse_Position) Reset()         { *m = UciResponse_Position{} }
func (m *UciResponse_Position) String() string { return proto.CompactTextString(m) }
func (*UciResponse_Position) ProtoMessage()    {}
func (*UciResponse_Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdc17040449aa6b8, []int{1, 1}
}

func (m *UciResponse_Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UciResponse_Position.Unmarshal(m, b)
}
func (m *UciResponse_Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UciResponse_Position.Marshal(b, m, deterministic)
}
func (m *UciResponse_Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UciResponse_Position.Merge(m, src)
}
func (m *UciResponse_Position) XXX_Size() int {
	return xxx_messageInfo_UciResponse_Position.Size(m)
}
func (m *UciResponse_Position) XXX_DiscardUnknown() {
	xxx_messageInfo_UciResponse_Position.DiscardUnknown(m)
}

var xxx_messageInfo_UciResponse_Position proto.InternalMessageInfo

func (m *UciResponse_Position) GetIsFen() bool {
	if m != nil {
		return m.IsFen
	}
	return false
}

func (m *UciResponse_Position) GetMoves() []string {
	if m != nil {
		return m.Moves
	}
	return nil
}

type UciResponse_Go struct {
	Searchmoves          []string `protobuf:"bytes,1,rep,name=searchmoves,proto3" json:"searchmoves,omitempty"`
	IsPonder             bool     `protobuf:"varint,2,opt,name=isPonder,proto3" json:"isPonder,omitempty"`
	Wtime                uint32   `protobuf:"varint,3,opt,name=wtime,proto3" json:"wtime,omitempty"`
	Btime                uint32   `protobuf:"varint,4,opt,name=btime,proto3" json:"btime,omitempty"`
	Winc                 uint32   `protobuf:"varint,5,opt,name=winc,proto3" json:"winc,omitempty"`
	Binc                 uint32   `protobuf:"varint,6,opt,name=binc,proto3" json:"binc,omitempty"`
	Movestogo            uint32   `protobuf:"varint,7,opt,name=movestogo,proto3" json:"movestogo,omitempty"`
	Depth                uint32   `protobuf:"varint,8,opt,name=depth,proto3" json:"depth,omitempty"`
	Nodes                uint32   `protobuf:"varint,9,opt,name=nodes,proto3" json:"nodes,omitempty"`
	Movetime             uint32   `protobuf:"varint,10,opt,name=movetime,proto3" json:"movetime,omitempty"`
	IsInfinite           bool     `protobuf:"varint,11,opt,name=isInfinite,proto3" json:"isInfinite,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UciResponse_Go) Reset()         { *m = UciResponse_Go{} }
func (m *UciResponse_Go) String() string { return proto.CompactTextString(m) }
func (*UciResponse_Go) ProtoMessage()    {}
func (*UciResponse_Go) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdc17040449aa6b8, []int{1, 2}
}

func (m *UciResponse_Go) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UciResponse_Go.Unmarshal(m, b)
}
func (m *UciResponse_Go) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UciResponse_Go.Marshal(b, m, deterministic)
}
func (m *UciResponse_Go) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UciResponse_Go.Merge(m, src)
}
func (m *UciResponse_Go) XXX_Size() int {
	return xxx_messageInfo_UciResponse_Go.Size(m)
}
func (m *UciResponse_Go) XXX_DiscardUnknown() {
	xxx_messageInfo_UciResponse_Go.DiscardUnknown(m)
}

var xxx_messageInfo_UciResponse_Go proto.InternalMessageInfo

func (m *UciResponse_Go) GetSearchmoves() []string {
	if m != nil {
		return m.Searchmoves
	}
	return nil
}

func (m *UciResponse_Go) GetIsPonder() bool {
	if m != nil {
		return m.IsPonder
	}
	return false
}

func (m *UciResponse_Go) GetWtime() uint32 {
	if m != nil {
		return m.Wtime
	}
	return 0
}

func (m *UciResponse_Go) GetBtime() uint32 {
	if m != nil {
		return m.Btime
	}
	return 0
}

func (m *UciResponse_Go) GetWinc() uint32 {
	if m != nil {
		return m.Winc
	}
	return 0
}

func (m *UciResponse_Go) GetBinc() uint32 {
	if m != nil {
		return m.Binc
	}
	return 0
}

func (m *UciResponse_Go) GetMovestogo() uint32 {
	if m != nil {
		return m.Movestogo
	}
	return 0
}

func (m *UciResponse_Go) GetDepth() uint32 {
	if m != nil {
		return m.Depth
	}
	return 0
}

func (m *UciResponse_Go) GetNodes() uint32 {
	if m != nil {
		return m.Nodes
	}
	return 0
}

func (m *UciResponse_Go) GetMovetime() uint32 {
	if m != nil {
		return m.Movetime
	}
	return 0
}

func (m *UciResponse_Go) GetIsInfinite() bool {
	if m != nil {
		return m.IsInfinite
	}
	return false
}

type Person struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rating               int32    `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdc17040449aa6b8, []int{2}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetRating() int32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

type RatingFilter struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RatingFilter) Reset()         { *m = RatingFilter{} }
func (m *RatingFilter) String() string { return proto.CompactTextString(m) }
func (*RatingFilter) ProtoMessage()    {}
func (*RatingFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdc17040449aa6b8, []int{3}
}

func (m *RatingFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RatingFilter.Unmarshal(m, b)
}
func (m *RatingFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RatingFilter.Marshal(b, m, deterministic)
}
func (m *RatingFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RatingFilter.Merge(m, src)
}
func (m *RatingFilter) XXX_Size() int {
	return xxx_messageInfo_RatingFilter.Size(m)
}
func (m *RatingFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_RatingFilter.DiscardUnknown(m)
}

var xxx_messageInfo_RatingFilter proto.InternalMessageInfo

type GameProposals struct {
	TimeControl          *TimeControl `protobuf:"bytes,1,opt,name=timeControl,proto3" json:"timeControl,omitempty"`
	Opponent             *Person      `protobuf:"bytes,2,opt,name=opponent,proto3" json:"opponent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GameProposals) Reset()         { *m = GameProposals{} }
func (m *GameProposals) String() string { return proto.CompactTextString(m) }
func (*GameProposals) ProtoMessage()    {}
func (*GameProposals) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdc17040449aa6b8, []int{4}
}

func (m *GameProposals) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameProposals.Unmarshal(m, b)
}
func (m *GameProposals) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameProposals.Marshal(b, m, deterministic)
}
func (m *GameProposals) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameProposals.Merge(m, src)
}
func (m *GameProposals) XXX_Size() int {
	return xxx_messageInfo_GameProposals.Size(m)
}
func (m *GameProposals) XXX_DiscardUnknown() {
	xxx_messageInfo_GameProposals.DiscardUnknown(m)
}

var xxx_messageInfo_GameProposals proto.InternalMessageInfo

func (m *GameProposals) GetTimeControl() *TimeControl {
	if m != nil {
		return m.TimeControl
	}
	return nil
}

func (m *GameProposals) GetOpponent() *Person {
	if m != nil {
		return m.Opponent
	}
	return nil
}

type GameControls struct {
	TimeControl          *TimeControl  `protobuf:"bytes,1,opt,name=timeControl,proto3" json:"timeControl,omitempty"`
	RatingFilter         *RatingFilter `protobuf:"bytes,2,opt,name=ratingFilter,proto3" json:"ratingFilter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GameControls) Reset()         { *m = GameControls{} }
func (m *GameControls) String() string { return proto.CompactTextString(m) }
func (*GameControls) ProtoMessage()    {}
func (*GameControls) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdc17040449aa6b8, []int{5}
}

func (m *GameControls) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameControls.Unmarshal(m, b)
}
func (m *GameControls) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameControls.Marshal(b, m, deterministic)
}
func (m *GameControls) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameControls.Merge(m, src)
}
func (m *GameControls) XXX_Size() int {
	return xxx_messageInfo_GameControls.Size(m)
}
func (m *GameControls) XXX_DiscardUnknown() {
	xxx_messageInfo_GameControls.DiscardUnknown(m)
}

var xxx_messageInfo_GameControls proto.InternalMessageInfo

func (m *GameControls) GetTimeControl() *TimeControl {
	if m != nil {
		return m.TimeControl
	}
	return nil
}

func (m *GameControls) GetRatingFilter() *RatingFilter {
	if m != nil {
		return m.RatingFilter
	}
	return nil
}

type Confimation struct {
	ConfimationCode      string   `protobuf:"bytes,1,opt,name=confimationCode,proto3" json:"confimationCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Confimation) Reset()         { *m = Confimation{} }
func (m *Confimation) String() string { return proto.CompactTextString(m) }
func (*Confimation) ProtoMessage()    {}
func (*Confimation) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdc17040449aa6b8, []int{6}
}

func (m *Confimation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Confimation.Unmarshal(m, b)
}
func (m *Confimation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Confimation.Marshal(b, m, deterministic)
}
func (m *Confimation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Confimation.Merge(m, src)
}
func (m *Confimation) XXX_Size() int {
	return xxx_messageInfo_Confimation.Size(m)
}
func (m *Confimation) XXX_DiscardUnknown() {
	xxx_messageInfo_Confimation.DiscardUnknown(m)
}

var xxx_messageInfo_Confimation proto.InternalMessageInfo

func (m *Confimation) GetConfimationCode() string {
	if m != nil {
		return m.ConfimationCode
	}
	return ""
}

type RoomRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomRequest) Reset()         { *m = RoomRequest{} }
func (m *RoomRequest) String() string { return proto.CompactTextString(m) }
func (*RoomRequest) ProtoMessage()    {}
func (*RoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdc17040449aa6b8, []int{7}
}

func (m *RoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomRequest.Unmarshal(m, b)
}
func (m *RoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomRequest.Marshal(b, m, deterministic)
}
func (m *RoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomRequest.Merge(m, src)
}
func (m *RoomRequest) XXX_Size() int {
	return xxx_messageInfo_RoomRequest.Size(m)
}
func (m *RoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoomRequest proto.InternalMessageInfo

type RoomMessage struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomMessage) Reset()         { *m = RoomMessage{} }
func (m *RoomMessage) String() string { return proto.CompactTextString(m) }
func (*RoomMessage) ProtoMessage()    {}
func (*RoomMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdc17040449aa6b8, []int{8}
}

func (m *RoomMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomMessage.Unmarshal(m, b)
}
func (m *RoomMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomMessage.Marshal(b, m, deterministic)
}
func (m *RoomMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomMessage.Merge(m, src)
}
func (m *RoomMessage) XXX_Size() int {
	return xxx_messageInfo_RoomMessage.Size(m)
}
func (m *RoomMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RoomMessage proto.InternalMessageInfo

func (m *RoomMessage) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GameRequestMessage struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameRequestMessage) Reset()         { *m = GameRequestMessage{} }
func (m *GameRequestMessage) String() string { return proto.CompactTextString(m) }
func (*GameRequestMessage) ProtoMessage()    {}
func (*GameRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdc17040449aa6b8, []int{9}
}

func (m *GameRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameRequestMessage.Unmarshal(m, b)
}
func (m *GameRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameRequestMessage.Marshal(b, m, deterministic)
}
func (m *GameRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameRequestMessage.Merge(m, src)
}
func (m *GameRequestMessage) XXX_Size() int {
	return xxx_messageInfo_GameRequestMessage.Size(m)
}
func (m *GameRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GameRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GameRequestMessage proto.InternalMessageInfo

func (m *GameRequestMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GameMessageResponse struct {
	Type                 GameMessageResponse_GameMessageResponseTypes `protobuf:"varint,1,opt,name=type,proto3,enum=GameMessageResponse_GameMessageResponseTypes" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                     `json:"-"`
	XXX_unrecognized     []byte                                       `json:"-"`
	XXX_sizecache        int32                                        `json:"-"`
}

func (m *GameMessageResponse) Reset()         { *m = GameMessageResponse{} }
func (m *GameMessageResponse) String() string { return proto.CompactTextString(m) }
func (*GameMessageResponse) ProtoMessage()    {}
func (*GameMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdc17040449aa6b8, []int{10}
}

func (m *GameMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameMessageResponse.Unmarshal(m, b)
}
func (m *GameMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameMessageResponse.Marshal(b, m, deterministic)
}
func (m *GameMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameMessageResponse.Merge(m, src)
}
func (m *GameMessageResponse) XXX_Size() int {
	return xxx_messageInfo_GameMessageResponse.Size(m)
}
func (m *GameMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GameMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GameMessageResponse proto.InternalMessageInfo

func (m *GameMessageResponse) GetType() GameMessageResponse_GameMessageResponseTypes {
	if m != nil {
		return m.Type
	}
	return GameMessageResponse_OK
}

type ClientGameMessage struct {
	MessageType          ClientGameMessage_MessageType `protobuf:"varint,1,opt,name=messageType,proto3,enum=ClientGameMessage_MessageType" json:"messageType,omitempty"`
	UciMessage           string                        `protobuf:"bytes,2,opt,name=uciMessage,proto3" json:"uciMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ClientGameMessage) Reset()         { *m = ClientGameMessage{} }
func (m *ClientGameMessage) String() string { return proto.CompactTextString(m) }
func (*ClientGameMessage) ProtoMessage()    {}
func (*ClientGameMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdc17040449aa6b8, []int{11}
}

func (m *ClientGameMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientGameMessage.Unmarshal(m, b)
}
func (m *ClientGameMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientGameMessage.Marshal(b, m, deterministic)
}
func (m *ClientGameMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientGameMessage.Merge(m, src)
}
func (m *ClientGameMessage) XXX_Size() int {
	return xxx_messageInfo_ClientGameMessage.Size(m)
}
func (m *ClientGameMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientGameMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ClientGameMessage proto.InternalMessageInfo

func (m *ClientGameMessage) GetMessageType() ClientGameMessage_MessageType {
	if m != nil {
		return m.MessageType
	}
	return ClientGameMessage_UCI
}

func (m *ClientGameMessage) GetUciMessage() string {
	if m != nil {
		return m.UciMessage
	}
	return ""
}

type GameState struct {
	Fen                  string       `protobuf:"bytes,1,opt,name=fen,proto3" json:"fen,omitempty"`
	TimeControl          *TimeControl `protobuf:"bytes,2,opt,name=timeControl,proto3" json:"timeControl,omitempty"`
	TimeState            *TimeState   `protobuf:"bytes,3,opt,name=timeState,proto3" json:"timeState,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GameState) Reset()         { *m = GameState{} }
func (m *GameState) String() string { return proto.CompactTextString(m) }
func (*GameState) ProtoMessage()    {}
func (*GameState) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdc17040449aa6b8, []int{12}
}

func (m *GameState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameState.Unmarshal(m, b)
}
func (m *GameState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameState.Marshal(b, m, deterministic)
}
func (m *GameState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameState.Merge(m, src)
}
func (m *GameState) XXX_Size() int {
	return xxx_messageInfo_GameState.Size(m)
}
func (m *GameState) XXX_DiscardUnknown() {
	xxx_messageInfo_GameState.DiscardUnknown(m)
}

var xxx_messageInfo_GameState proto.InternalMessageInfo

func (m *GameState) GetFen() string {
	if m != nil {
		return m.Fen
	}
	return ""
}

func (m *GameState) GetTimeControl() *TimeControl {
	if m != nil {
		return m.TimeControl
	}
	return nil
}

func (m *GameState) GetTimeState() *TimeState {
	if m != nil {
		return m.TimeState
	}
	return nil
}

type TimeControl struct {
	Time                 int32    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Incremet             int32    `protobuf:"varint,2,opt,name=incremet,proto3" json:"incremet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeControl) Reset()         { *m = TimeControl{} }
func (m *TimeControl) String() string { return proto.CompactTextString(m) }
func (*TimeControl) ProtoMessage()    {}
func (*TimeControl) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdc17040449aa6b8, []int{13}
}

func (m *TimeControl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeControl.Unmarshal(m, b)
}
func (m *TimeControl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeControl.Marshal(b, m, deterministic)
}
func (m *TimeControl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeControl.Merge(m, src)
}
func (m *TimeControl) XXX_Size() int {
	return xxx_messageInfo_TimeControl.Size(m)
}
func (m *TimeControl) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeControl.DiscardUnknown(m)
}

var xxx_messageInfo_TimeControl proto.InternalMessageInfo

func (m *TimeControl) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *TimeControl) GetIncremet() int32 {
	if m != nil {
		return m.Incremet
	}
	return 0
}

type TimeState struct {
	WhiteTimeRemaining   int32    `protobuf:"varint,1,opt,name=whiteTimeRemaining,proto3" json:"whiteTimeRemaining,omitempty"`
	BlackTimeRemaining   int32    `protobuf:"varint,2,opt,name=blackTimeRemaining,proto3" json:"blackTimeRemaining,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeState) Reset()         { *m = TimeState{} }
func (m *TimeState) String() string { return proto.CompactTextString(m) }
func (*TimeState) ProtoMessage()    {}
func (*TimeState) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdc17040449aa6b8, []int{14}
}

func (m *TimeState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeState.Unmarshal(m, b)
}
func (m *TimeState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeState.Marshal(b, m, deterministic)
}
func (m *TimeState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeState.Merge(m, src)
}
func (m *TimeState) XXX_Size() int {
	return xxx_messageInfo_TimeState.Size(m)
}
func (m *TimeState) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeState.DiscardUnknown(m)
}

var xxx_messageInfo_TimeState proto.InternalMessageInfo

func (m *TimeState) GetWhiteTimeRemaining() int32 {
	if m != nil {
		return m.WhiteTimeRemaining
	}
	return 0
}

func (m *TimeState) GetBlackTimeRemaining() int32 {
	if m != nil {
		return m.BlackTimeRemaining
	}
	return 0
}

type ServerGameMessage struct {
	MessageType          ServerGameMessage_MessageType `protobuf:"varint,1,opt,name=messageType,proto3,enum=ServerGameMessage_MessageType" json:"messageType,omitempty"`
	UciMessage           string                        `protobuf:"bytes,2,opt,name=uciMessage,proto3" json:"uciMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ServerGameMessage) Reset()         { *m = ServerGameMessage{} }
func (m *ServerGameMessage) String() string { return proto.CompactTextString(m) }
func (*ServerGameMessage) ProtoMessage()    {}
func (*ServerGameMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdc17040449aa6b8, []int{15}
}

func (m *ServerGameMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerGameMessage.Unmarshal(m, b)
}
func (m *ServerGameMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerGameMessage.Marshal(b, m, deterministic)
}
func (m *ServerGameMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerGameMessage.Merge(m, src)
}
func (m *ServerGameMessage) XXX_Size() int {
	return xxx_messageInfo_ServerGameMessage.Size(m)
}
func (m *ServerGameMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerGameMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ServerGameMessage proto.InternalMessageInfo

func (m *ServerGameMessage) GetMessageType() ServerGameMessage_MessageType {
	if m != nil {
		return m.MessageType
	}
	return ServerGameMessage_UCI
}

func (m *ServerGameMessage) GetUciMessage() string {
	if m != nil {
		return m.UciMessage
	}
	return ""
}

func init() {
	proto.RegisterEnum("UciRequest_MessageType", UciRequest_MessageType_name, UciRequest_MessageType_value)
	proto.RegisterEnum("UciResponse_MessageType", UciResponse_MessageType_name, UciResponse_MessageType_value)
	proto.RegisterEnum("GameMessageResponse_GameMessageResponseTypes", GameMessageResponse_GameMessageResponseTypes_name, GameMessageResponse_GameMessageResponseTypes_value)
	proto.RegisterEnum("ClientGameMessage_MessageType", ClientGameMessage_MessageType_name, ClientGameMessage_MessageType_value)
	proto.RegisterEnum("ServerGameMessage_MessageType", ServerGameMessage_MessageType_name, ServerGameMessage_MessageType_value)
	proto.RegisterType((*UciRequest)(nil), "UciRequest")
	proto.RegisterType((*UciRequest_Option)(nil), "UciRequest.Option")
	proto.RegisterType((*UciRequest_Id)(nil), "UciRequest.Id")
	proto.RegisterType((*UciRequest_BestMove)(nil), "UciRequest.BestMove")
	proto.RegisterType((*UciRequest_Score)(nil), "UciRequest.Score")
	proto.RegisterType((*UciRequest_Info)(nil), "UciRequest.Info")
	proto.RegisterType((*UciResponse)(nil), "UciResponse")
	proto.RegisterType((*UciResponse_SetOption)(nil), "UciResponse.SetOption")
	proto.RegisterType((*UciResponse_Position)(nil), "UciResponse.Position")
	proto.RegisterType((*UciResponse_Go)(nil), "UciResponse.Go")
	proto.RegisterType((*Person)(nil), "Person")
	proto.RegisterType((*RatingFilter)(nil), "RatingFilter")
	proto.RegisterType((*GameProposals)(nil), "GameProposals")
	proto.RegisterType((*GameControls)(nil), "GameControls")
	proto.RegisterType((*Confimation)(nil), "Confimation")
	proto.RegisterType((*RoomRequest)(nil), "RoomRequest")
	proto.RegisterType((*RoomMessage)(nil), "RoomMessage")
	proto.RegisterType((*GameRequestMessage)(nil), "GameRequestMessage")
	proto.RegisterType((*GameMessageResponse)(nil), "GameMessageResponse")
	proto.RegisterType((*ClientGameMessage)(nil), "ClientGameMessage")
	proto.RegisterType((*GameState)(nil), "GameState")
	proto.RegisterType((*TimeControl)(nil), "TimeControl")
	proto.RegisterType((*TimeState)(nil), "TimeState")
	proto.RegisterType((*ServerGameMessage)(nil), "ServerGameMessage")
}

func init() { proto.RegisterFile("service/chess.proto", fileDescriptor_cdc17040449aa6b8) }

var fileDescriptor_cdc17040449aa6b8 = []byte{
	// 1396 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xcb, 0x6e, 0xdb, 0x46,
	0x14, 0x35, 0x69, 0x4b, 0x26, 0xaf, 0x1e, 0x61, 0x26, 0x69, 0x42, 0x08, 0x45, 0x6a, 0xb0, 0x41,
	0x6a, 0x14, 0xa8, 0x92, 0xb8, 0x69, 0x8b, 0x06, 0x28, 0x50, 0x47, 0x66, 0x5c, 0x22, 0xb1, 0xa9,
	0x8c, 0xe4, 0x06, 0x59, 0x05, 0x14, 0x35, 0xb2, 0x88, 0x50, 0x1c, 0x86, 0xa4, 0xe4, 0x74, 0xd7,
	0x2f, 0xe8, 0xaa, 0xcb, 0x6e, 0xdb, 0x5d, 0x7f, 0xa3, 0x7f, 0xd3, 0x7f, 0x28, 0xee, 0xcc, 0x50,
	0xa2, 0x1c, 0xb9, 0xaf, 0xdd, 0x9c, 0x73, 0xcf, 0xdc, 0x79, 0xdc, 0x07, 0x87, 0x70, 0x23, 0x67,
	0xd9, 0x22, 0x0a, 0xd9, 0xfd, 0x70, 0xca, 0xf2, 0xbc, 0x9b, 0x66, 0xbc, 0xe0, 0xce, 0x1f, 0x06,
	0xc0, 0x59, 0x18, 0x51, 0xf6, 0x76, 0xce, 0xf2, 0x82, 0x7c, 0x0d, 0x8d, 0x19, 0xcb, 0xf3, 0xe0,
	0x9c, 0x0d, 0x7f, 0x48, 0x99, 0xad, 0xed, 0x69, 0xfb, 0xed, 0x83, 0xdb, 0xdd, 0x95, 0xa2, 0x7b,
	0xb2, 0x32, 0xd3, 0xaa, 0x96, 0xdc, 0x01, 0x3d, 0x1a, 0xdb, 0xfa, 0x9e, 0xb6, 0xdf, 0x38, 0x68,
	0x57, 0x67, 0x78, 0x63, 0xaa, 0x47, 0x63, 0xf2, 0x00, 0x8c, 0x11, 0xcb, 0x8b, 0x13, 0xbe, 0x60,
	0xf6, 0xb6, 0x50, 0xdd, 0xac, 0xaa, 0x9e, 0x28, 0x1b, 0x5d, 0xaa, 0xc8, 0x5d, 0xd8, 0x89, 0x92,
	0x09, 0xb7, 0x77, 0x84, 0xda, 0x5a, 0xf3, 0x99, 0x4c, 0x38, 0x15, 0x56, 0xf2, 0x29, 0xd4, 0x79,
	0x5a, 0x44, 0x3c, 0xb1, 0x6b, 0x42, 0x47, 0xaa, 0x3a, 0x5f, 0x58, 0xa8, 0x52, 0x74, 0x7e, 0xd4,
	0xa0, 0x2e, 0x29, 0x42, 0x60, 0x27, 0x09, 0x66, 0xf2, 0x88, 0x26, 0x15, 0x63, 0xe4, 0x0a, 0x3c,
	0xb6, 0x2e, 0x39, 0x1c, 0x13, 0x1b, 0x76, 0xc7, 0x6c, 0x12, 0xcc, 0xe3, 0x42, 0xec, 0xda, 0xa4,
	0x25, 0x24, 0x16, 0x6c, 0xcf, 0xa2, 0x44, 0xec, 0xae, 0x46, 0x71, 0x28, 0x98, 0xe0, 0x9d, 0xd8,
	0x07, 0x32, 0xc1, 0x3b, 0x64, 0x16, 0x41, 0x66, 0xd7, 0xf7, 0xb6, 0xf7, 0x4d, 0x8a, 0xc3, 0xce,
	0x03, 0xd0, 0xbd, 0xf1, 0xc6, 0xd5, 0x6f, 0x41, 0x3d, 0x98, 0x17, 0x53, 0x9e, 0xa9, 0xf5, 0x15,
	0xea, 0x38, 0x60, 0x94, 0x97, 0x83, 0x9a, 0x94, 0x27, 0x63, 0x96, 0xd9, 0x9a, 0x70, 0xa9, 0x50,
	0xe7, 0x25, 0xd4, 0x06, 0x21, 0xcf, 0x18, 0x69, 0x83, 0x1e, 0xa6, 0xc2, 0x6d, 0x8d, 0xea, 0x61,
	0x8a, 0x0b, 0xcd, 0x82, 0x42, 0x1e, 0xa9, 0x46, 0xc5, 0x98, 0xdc, 0x84, 0x5a, 0xcc, 0x2f, 0x58,
	0x26, 0x0e, 0x54, 0xa3, 0x12, 0x20, 0x3b, 0x4f, 0x53, 0x96, 0xa9, 0x03, 0x49, 0xd0, 0xf9, 0x7d,
	0x1b, 0x76, 0xf0, 0xb2, 0xd1, 0x3c, 0x66, 0x69, 0x31, 0x15, 0xbe, 0x5b, 0x54, 0x02, 0xd2, 0x01,
	0x23, 0x67, 0xb1, 0x34, 0xe8, 0xc2, 0xb0, 0xc4, 0xe2, 0x36, 0xa3, 0x99, 0x0c, 0x76, 0x8b, 0x8a,
	0x31, 0x7a, 0x49, 0xf8, 0x98, 0xe5, 0x62, 0x91, 0x16, 0x95, 0x00, 0x37, 0x9d, 0x2e, 0xd4, 0xb5,
	0xe9, 0xe9, 0x02, 0xef, 0x7c, 0x36, 0x8f, 0x8b, 0x28, 0x5d, 0xd8, 0x75, 0x41, 0x96, 0x90, 0x7c,
	0x02, 0xb5, 0x1c, 0xcf, 0x69, 0xef, 0x8a, 0x58, 0x5f, 0xaf, 0xc6, 0x5a, 0x5c, 0x00, 0x95, 0x76,
	0xdc, 0x58, 0x38, 0xcf, 0xb2, 0x19, 0x66, 0x9b, 0x21, 0xae, 0x73, 0x89, 0xc9, 0x3d, 0x68, 0x97,
	0xe3, 0x64, 0x3e, 0x1b, 0xb1, 0xcc, 0x36, 0xc5, 0x6e, 0x2e, 0xb1, 0xe8, 0x63, 0x1a, 0xe4, 0xd3,
	0xc9, 0x3c, 0x8e, 0x6d, 0x90, 0x87, 0x2b, 0x31, 0x06, 0x36, 0x49, 0x73, 0xbb, 0x21, 0x68, 0x1c,
	0x62, 0x68, 0x8a, 0xd1, 0x34, 0x2a, 0x72, 0xbb, 0x29, 0x48, 0x85, 0xf0, 0x30, 0x61, 0x3a, 0x8f,
	0x79, 0x30, 0xb6, 0x5b, 0xc2, 0x50, 0x42, 0x9c, 0x91, 0x17, 0x59, 0x94, 0x9c, 0xdb, 0x6d, 0x19,
	0x70, 0x89, 0xc8, 0x1d, 0x80, 0x8c, 0x4d, 0xe6, 0x45, 0x20, 0xb2, 0xfa, 0x9a, 0x08, 0x74, 0x85,
	0x29, 0xcf, 0x16, 0x47, 0x09, 0xb3, 0xad, 0xd5, 0xd9, 0x10, 0x3b, 0x17, 0xd0, 0xa8, 0x54, 0x28,
	0xa9, 0x83, 0xee, 0x1d, 0x59, 0x5b, 0x04, 0xa0, 0xee, 0xf7, 0x87, 0x9e, 0x7f, 0x6a, 0x69, 0xc4,
	0x84, 0xda, 0x59, 0xcf, 0xf3, 0x9f, 0x59, 0x3a, 0x69, 0xc0, 0x2e, 0x75, 0x0f, 0x8f, 0x5e, 0xf9,
	0xcf, 0xac, 0x6d, 0xd2, 0x04, 0xe3, 0x89, 0x3b, 0x18, 0x9e, 0xf8, 0xdf, 0xbb, 0xd6, 0x0e, 0x21,
	0xd0, 0xee, 0xf9, 0xfd, 0x57, 0x7d, 0xea, 0x0f, 0xdd, 0x9e, 0x98, 0x59, 0x23, 0x16, 0x34, 0xa9,
	0x7b, 0xec, 0x0d, 0x86, 0xf4, 0x50, 0x30, 0x75, 0x62, 0xc0, 0x8e, 0x77, 0xfa, 0xd4, 0xb7, 0x76,
	0x9d, 0x3f, 0x6b, 0xd0, 0x10, 0xc1, 0xc8, 0x53, 0x9e, 0xe4, 0x8c, 0x3c, 0xde, 0xd4, 0x49, 0xec,
	0x6e, 0x45, 0x72, 0x75, 0x2b, 0x11, 0xb9, 0x36, 0x9a, 0x9f, 0x8b, 0x94, 0x32, 0xa8, 0x04, 0xe4,
	0x11, 0x98, 0x39, 0x2b, 0x64, 0xf9, 0xaa, 0x0e, 0x72, 0x6b, 0xcd, 0xdf, 0xa0, 0xb4, 0xd2, 0x95,
	0x90, 0x3c, 0x04, 0x23, 0xe5, 0x79, 0x24, 0x26, 0xc9, 0x46, 0xf2, 0xc1, 0xda, 0xa4, 0xbe, 0x32,
	0xd2, 0xa5, 0xac, 0xf3, 0x05, 0x98, 0x4b, 0x57, 0x1b, 0x2b, 0xf5, 0x26, 0xd4, 0x16, 0x41, 0x3c,
	0x2f, 0x1b, 0x85, 0x04, 0x9d, 0x2f, 0xc1, 0x28, 0x9d, 0xa1, 0x22, 0xca, 0x9f, 0xb2, 0x44, 0x4c,
	0x33, 0xa8, 0x04, 0xc8, 0x62, 0x7a, 0xe5, 0xb6, 0x2e, 0x62, 0x2a, 0x41, 0xe7, 0x17, 0x1d, 0xf4,
	0x63, 0x4e, 0xf6, 0xa0, 0x91, 0xb3, 0x20, 0x0b, 0xa7, 0x52, 0x22, 0xeb, 0xbb, 0x4a, 0x61, 0xdc,
	0xa3, 0xbc, 0x2f, 0xcb, 0x5f, 0xde, 0xcc, 0x12, 0xa3, 0xeb, 0x8b, 0x4a, 0xb5, 0x49, 0x80, 0xec,
	0x48, 0xb0, 0xaa, 0xdc, 0x04, 0xc0, 0x23, 0x5d, 0x44, 0x49, 0x28, 0x0a, 0xae, 0x45, 0xc5, 0x18,
	0xb9, 0x11, 0x72, 0x75, 0xc9, 0xe1, 0x98, 0x7c, 0x08, 0xa6, 0x58, 0xb8, 0xe0, 0xe7, 0x5c, 0x14,
	0x5c, 0x8b, 0xae, 0x88, 0x55, 0x43, 0x30, 0xaa, 0x0d, 0x61, 0x59, 0xe0, 0x66, 0xb5, 0xc0, 0x3b,
	0x60, 0xe0, 0x44, 0xb1, 0x15, 0x55, 0x49, 0x25, 0xc6, 0x6c, 0x8f, 0x72, 0x2f, 0x99, 0x44, 0x49,
	0x54, 0x30, 0x51, 0x50, 0x06, 0xad, 0x30, 0xce, 0xcf, 0xda, 0x7a, 0x4a, 0xef, 0xc2, 0xf6, 0x59,
	0xcf, 0xb3, 0xb6, 0x30, 0x8f, 0x8f, 0xdc, 0x27, 0x67, 0xc7, 0x96, 0x86, 0x79, 0xec, 0x0d, 0x44,
	0x26, 0x5b, 0x3a, 0x69, 0x81, 0x39, 0x70, 0x87, 0x2a, 0xdd, 0x45, 0x5a, 0xcb, 0xa4, 0x75, 0xa9,
	0xb5, 0x43, 0xda, 0x00, 0x67, 0x3d, 0xef, 0xd4, 0x7d, 0x79, 0x7c, 0x78, 0xe2, 0x5a, 0x35, 0xb4,
	0xf6, 0xfd, 0x81, 0xa7, 0xd2, 0xb9, 0x0e, 0xfa, 0xb1, 0x6f, 0xed, 0x62, 0x5a, 0x0f, 0x86, 0x7e,
	0xdf, 0x32, 0xd0, 0x59, 0xdf, 0x3f, 0x3d, 0x72, 0xe9, 0x77, 0xde, 0xd0, 0x32, 0xd1, 0xf0, 0xe2,
	0xcc, 0x1b, 0x5a, 0xe0, 0x1c, 0x41, 0xbd, 0xcf, 0xb2, 0x9c, 0x27, 0xd8, 0xbd, 0xa2, 0xb1, 0xca,
	0x0f, 0xfc, 0xd0, 0x95, 0x19, 0xa3, 0xaf, 0xf7, 0xf6, 0x2c, 0x28, 0xb0, 0xd4, 0x65, 0xcf, 0x55,
	0xc8, 0x69, 0x43, 0x93, 0x8a, 0xd1, 0xd3, 0x28, 0x2e, 0x58, 0xe6, 0x8c, 0xa1, 0x75, 0x1c, 0xcc,
	0x58, 0x3f, 0xe3, 0x29, 0xcf, 0x83, 0x38, 0x27, 0x5d, 0x68, 0xe0, 0x2d, 0xf5, 0x78, 0x52, 0x64,
	0x3c, 0x16, 0xab, 0x34, 0x0e, 0x9a, 0xdd, 0xe1, 0x8a, 0xa3, 0x55, 0x01, 0xf9, 0x18, 0x0c, 0x9e,
	0xa6, 0x3c, 0x61, 0x49, 0xa1, 0xbe, 0xc5, 0xbb, 0x5d, 0xb9, 0x4f, 0xba, 0x34, 0x38, 0x6f, 0xa1,
	0x89, 0xab, 0xa8, 0x39, 0xff, 0x7d, 0x91, 0x87, 0xd0, 0xcc, 0x2a, 0xbb, 0x56, 0x0b, 0xb5, 0xba,
	0xd5, 0xa3, 0xd0, 0x35, 0x89, 0xf3, 0x15, 0x34, 0x7a, 0x3c, 0x99, 0x44, 0x33, 0xd9, 0xc2, 0xf6,
	0xe1, 0x5a, 0xb8, 0x82, 0x3d, 0x3e, 0x2e, 0x0b, 0xec, 0x32, 0xed, 0xb4, 0xa0, 0x41, 0x39, 0x9f,
	0xa9, 0x26, 0xef, 0x7c, 0x24, 0xa1, 0x4a, 0x08, 0xf1, 0xc5, 0xcd, 0xcf, 0xd5, 0x5c, 0x1c, 0x3a,
	0x77, 0x81, 0xe0, 0xd9, 0x94, 0xbe, 0xd4, 0x5d, 0x8a, 0x91, 0xf3, 0x93, 0x06, 0x37, 0x50, 0xa6,
	0xec, 0xcb, 0xae, 0x75, 0xa8, 0x5e, 0x00, 0xb2, 0x5d, 0x7d, 0xd6, 0xdd, 0xa0, 0xd9, 0xc4, 0x61,
	0x62, 0xe6, 0xf2, 0xc1, 0xe0, 0x3c, 0x02, 0xfb, 0x2a, 0x05, 0xe6, 0x97, 0xff, 0xcc, 0xda, 0xc2,
	0x46, 0xea, 0x3d, 0x7f, 0xee, 0x1e, 0x1f, 0x3e, 0x7f, 0x2d, 0xda, 0xad, 0xe6, 0xfc, 0xaa, 0xc1,
	0xf5, 0x5e, 0x1c, 0xb1, 0xa4, 0xa8, 0x4c, 0x26, 0xdf, 0x6e, 0x6a, 0xa2, 0x77, 0xba, 0xef, 0x09,
	0xff, 0xee, 0x55, 0x06, 0xf3, 0x30, 0x52, 0x66, 0x95, 0x92, 0x15, 0xc6, 0xe9, 0x5e, 0x51, 0x5c,
	0xb7, 0x80, 0x60, 0x85, 0xbc, 0x1e, 0x0c, 0x0f, 0x87, 0xee, 0x6b, 0xea, 0xbe, 0x38, 0x73, 0x07,
	0x43, 0x4b, 0x73, 0x2e, 0xc0, 0xc4, 0x75, 0x07, 0x05, 0x3e, 0x24, 0x2c, 0xd8, 0x9e, 0xa8, 0x1e,
	0x67, 0x52, 0x1c, 0x5e, 0xce, 0x24, 0xfd, 0x9f, 0x32, 0x69, 0x1f, 0x4c, 0x84, 0xc2, 0x9d, 0xea,
	0xe9, 0x20, 0xd4, 0x82, 0xa1, 0x2b, 0xa3, 0xf3, 0x0d, 0x34, 0x2a, 0x5e, 0x96, 0x8f, 0x0b, 0xf9,
	0xd2, 0x91, 0x8f, 0x0b, 0xec, 0x8f, 0x49, 0x98, 0xb1, 0x19, 0x2b, 0xd4, 0x7b, 0x67, 0x89, 0x9d,
	0x37, 0x60, 0x2e, 0xdd, 0x92, 0x2e, 0x90, 0x8b, 0x69, 0x54, 0x30, 0x64, 0x28, 0x9b, 0x05, 0x51,
	0x82, 0x95, 0x29, 0x5d, 0x6d, 0xb0, 0xa0, 0x7e, 0x14, 0x07, 0xe1, 0x9b, 0x75, 0xbd, 0x5c, 0x62,
	0x83, 0xc5, 0xf9, 0x4d, 0x83, 0xeb, 0x03, 0x96, 0x2d, 0x58, 0xf6, 0x2f, 0x82, 0xf9, 0x9e, 0xf0,
	0xff, 0x07, 0xf3, 0xfe, 0x15, 0xc1, 0xbc, 0x0d, 0x37, 0xd6, 0x82, 0x39, 0xe8, 0xfb, 0xa7, 0x03,
	0xd7, 0xd2, 0x0e, 0x1e, 0x83, 0xd5, 0xc3, 0x9f, 0x81, 0xc3, 0x34, 0x8d, 0xa3, 0x50, 0x96, 0xe6,
	0x3d, 0x31, 0x8b, 0x34, 0x2a, 0x4f, 0xab, 0x4e, 0xb3, 0xfa, 0xc9, 0x74, 0xb6, 0xf6, 0xb5, 0x07,
	0xda, 0xa8, 0x2e, 0x7e, 0x20, 0x3e, 0xff, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xde, 0x74, 0xa7, 0xfc,
	0x57, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChessApplicationClient is the client API for ChessApplication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChessApplicationClient interface {
	UCI(ctx context.Context, opts ...grpc.CallOption) (ChessApplication_UCIClient, error)
}

type chessApplicationClient struct {
	cc *grpc.ClientConn
}

func NewChessApplicationClient(cc *grpc.ClientConn) ChessApplicationClient {
	return &chessApplicationClient{cc}
}

func (c *chessApplicationClient) UCI(ctx context.Context, opts ...grpc.CallOption) (ChessApplication_UCIClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ChessApplication_serviceDesc.Streams[0], "/ChessApplication/UCI", opts...)
	if err != nil {
		return nil, err
	}
	x := &chessApplicationUCIClient{stream}
	return x, nil
}

type ChessApplication_UCIClient interface {
	Send(*UciRequest) error
	Recv() (*UciResponse, error)
	grpc.ClientStream
}

type chessApplicationUCIClient struct {
	grpc.ClientStream
}

func (x *chessApplicationUCIClient) Send(m *UciRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chessApplicationUCIClient) Recv() (*UciResponse, error) {
	m := new(UciResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChessApplicationServer is the server API for ChessApplication service.
type ChessApplicationServer interface {
	UCI(ChessApplication_UCIServer) error
}

// UnimplementedChessApplicationServer can be embedded to have forward compatible implementations.
type UnimplementedChessApplicationServer struct {
}

func (*UnimplementedChessApplicationServer) UCI(srv ChessApplication_UCIServer) error {
	return status.Errorf(codes.Unimplemented, "method UCI not implemented")
}

func RegisterChessApplicationServer(s *grpc.Server, srv ChessApplicationServer) {
	s.RegisterService(&_ChessApplication_serviceDesc, srv)
}

func _ChessApplication_UCI_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChessApplicationServer).UCI(&chessApplicationUCIServer{stream})
}

type ChessApplication_UCIServer interface {
	Send(*UciResponse) error
	Recv() (*UciRequest, error)
	grpc.ServerStream
}

type chessApplicationUCIServer struct {
	grpc.ServerStream
}

func (x *chessApplicationUCIServer) Send(m *UciResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chessApplicationUCIServer) Recv() (*UciRequest, error) {
	m := new(UciRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ChessApplication_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ChessApplication",
	HandlerType: (*ChessApplicationServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UCI",
			Handler:       _ChessApplication_UCI_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "service/chess.proto",
}
